<a href="https://colab.research.google.com/github/ashish06-official/Starter/blob/main/Titanic%20Survival%20Prediction/Titanic_Survival_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
import warnings
warnings.filterwarnings("ignore")

titanic_data = pd.read_csv("/content/Titanic_Dataset.csv")
pd.set_option('display.max_columns',None)
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:

titanic_data.info()
print(titanic_data.isnull().sum())

titanic_data['Survived'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Survived
0    549
1    342
Name: count, dtype: int64

In [3]:
titanic_data.drop(columns = ["PassengerId","Ticket","Cabin"],inplace = True)
titanic_data["Age"].fillna(titanic_data["Age"].median(), inplace = True)

pd.set_option("display.max_columns",None)
titanic_data.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S

In [4]:
titanic_data["Embarked"].value_counts()
titanic_data["Embarked"].fillna(titanic_data["Embarked"].mode()[0],inplace = True)
titanic_data.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [5]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Fare      891 non-null    float64
 8   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [6]:
titanic_data["Embarked"] = titanic_data["Embarked"].map({"S":0,"C":1,"Q":2})
titanic_data["Sex"] = titanic_data["Sex"].map({"male":0,"female":1})
titanic_data.head()

titanic_data.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [7]:
x = titanic_data.drop(columns=["Survived", "Name"])
y = titanic_data["Survived"]
xtrain , xtest , ytrain , ytest = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [8]:
model = RandomForestClassifier()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)

In [9]:
acc = accuracy_score(ytest,ypred)
print(acc)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8324022346368715
[[92 13]
 [17 57]]
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       105
           1       0.81      0.77      0.79        74

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.83       179
weighted avg       0.83      0.83      0.83       179